"""
string -> ''
number -> 8
boolean -> True or False
-------------- 
list -> []
dict -> {}
funcoes -> def ()
"""

lista = [
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
    {'nome': "alberto"},
    {'nome': "jean"},
    {'nome': "andre"},
    {'nome': "bam"},
]

#                Valor incial, Valor final, De quanto em quanto. 
for index in range(0, 10, 2):
    print(lista[index])